import { List } from './list';

export const C_LIST: List[] = [
  {  name: 'Autocomplete', source: 'https://material.angular.io/assets/screenshots/autocomplete.scene.png', description:'Suggests relevant options as the user types.'},
  {  name: 'Badge', source:'https://material.angular.io/assets/screenshots/badge.scene.png', description:'A small value indicator that can be overlaid on another object.' },
  {  name: 'Bottom Sheet', source:'https://material.angular.io/assets/screenshots/bottom-sheet.scene.png', description:'A large interactive panel primarily for mobile devices.' },
  {  name: 'Button', source: 'https://material.angular.io/assets/screenshots/button.scene.png', description:'An interactive button with a range of presentation options.'},
  {  name: 'Button toggle', source: 'https://material.angular.io/assets/screenshots/button-toggle.scene.png', description:'A groupable on/off toggle for enabling and disabling options.'},
  {  name: 'Card', source: 'https://material.angular.io/assets/screenshots/card.scene.png', description:'A styled container for pieces of itemized content.'},
  {  name: 'Checkbox' , source:'https://material.angular.io/assets/screenshots/checkbox.scene.png', description:'Captures boolean input with an optional indeterminate mode.'},
  {  name: 'Chips', source: 'https://material.angular.io/assets/screenshots/chips.scene.png', description:'Presents a list of items as a set of small, tactile entities.'},
  {  name: 'Core' , source:'https://material.angular.io/assets/screenshots/core.scene.png', description:'Reusable parts used by other components in the library.'},
  {  name: 'Datepicker', source:'https://material.angular.io/assets/screenshots/datepicker.scene.png', description:'Captures dates, agnostic about their internal representation.' },
  {  name: 'Dialog', source:'https://material.angular.io/assets/screenshots/dialog.scene.png' , description:'A configurable modal that displays dynamic content.'},
  {  name: 'Divider',source:'https://material.angular.io/assets/screenshots/divider.scene.png', description:'A vertical or horizontal visual divider.' },
  {  name: 'Expansion Panel' , source:'https://material.angular.io/assets/screenshots/expansion.scene.png' , description:'A container which can be expanded to reveal more content.'},
  {  name: 'Form field' , source: 'https://material.angular.io/assets/screenshots/form-field.scene.png', description:'Wraps input fields so they are displayed consistently.'},
  {  name: 'Grid list' , source:'https://material.angular.io/assets/screenshots/grid-list.scene.png', description:'A flexible structure for presenting content items in a grid.'},
  {  name: 'Icon' , source:'https://material.angular.io/assets/screenshots/icon.scene.png', description:'Renders a specified icon.'},
  {  name: 'Input', source:'https://material.angular.io/assets/screenshots/input.scene.png' , description:'Enables native inputs to be used within a Form field.'},
  {  name: 'List' , source:'https://material.angular.io/assets/screenshots/list.scene.png', description:'Presents conventional lists of items.'},
  {  name: 'Menu' , source:'https://material.angular.io/assets/screenshots/menu.scene.png', description:'A floating panel of nestable options.'},
  {  name: 'Paginator', source:'https://material.angular.io/assets/screenshots/paginator.scene.png', description:'Controls for displaying paged data.' },
  {  name: 'Progress bar', source:'https://material.angular.io/assets/screenshots/progress-bar.scene.png', description:'A linear progress indicator.' },
  {  name: 'Progress spinner', source:'https://material.angular.io/assets/screenshots/progress-spinner.scene.png', description:'A circular progress indicator.' },
  {  name: 'Radio button', source:'https://material.angular.io/assets/screenshots/radio.scene.png' , description:'Allows the user to select one option from a group.' },
  {  name: 'Ripples', source: 'https://material.angular.io/assets/screenshots/ripple.scene.png', description:'Directive for adding Material Design ripple effects'},
  {  name: 'Select', source: 'https://material.angular.io/assets/screenshots/select.scene.png', description:'Allows the user to select one or more options using a dropdown.'},
  {  name: 'Sidenav', source: 'https://material.angular.io/assets/screenshots/sidenav.scene.png', description:'A container for content that is fixed to one side of the screen.'},
  {  name: 'Slide toggle', source:'https://material.angular.io/assets/screenshots/slide-toggle.scene.png', description:'Captures boolean values as a clickable and draggable switch.' },
  {  name: 'Slider', source: 'https://material.angular.io/assets/screenshots/slider.scene.png', description:'Allows the user to input a value by dragging along a slider.'},
  {  name: 'Snackbar', source:'https://material.angular.io/assets/screenshots/snack-bar.scene.png' , description:'Displays short actionable messages as an uninvasive alert.'},
  {  name: 'Sort Header' , source:'https://material.angular.io/assets/screenshots/sort.scene.png', description:'Allows the user to configure how tabular data is sorted.'},
  {  name: 'Stepper' , source:'https://material.angular.io/assets/screenshots/stepper.scene.png', description:'Presents content as steps through which to progress.'},
  {  name: 'Table' , source:'https://material.angular.io/assets/screenshots/table.scene.png', description:'A configurable component for displaying tabular data.'},
  {  name: 'Tabs' , source:'https://material.angular.io/assets/screenshots/tabs.scene.png', description:'Only presents one view at a time from a provided set of views.'},
  {  name: 'Toolbar' , source:'https://material.angular.io/assets/screenshots/toolbar.scene.png', description:'A container for top-level titles and controls.'},
  {  name: 'Tooltip' , source:'https://material.angular.io/assets/screenshots/tooltip.scene.png', description:'Displays floating content when an object is hovered.'},
  {  name: 'Tree' , source:'https://material.angular.io/assets/screenshots/tree.scene.png', description:'Presents hierarchical content as an expandable tree.'},
 
];